### ISSUE TITLE
Could not find com.google.android.flexbox:flexbox:2.0.1.

### ISSUE THREAD

**Issue by angelgoitia** [raj-wv/flutter_zoom#8]
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.android.flexbox:flexbox:2.0.1.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by raj-wv** [comment]
> angelgoitia

i think you need to upgrade your gradle version to 7.2.1

**Comment by angelgoitia** [comment]
yes thanks, after investigating it did not work for me I saw the example of the project and updated the gradle, it would be good to notify it in README.md what version of flutter I use, version of gradle and the zoom sdk version

**Comment by raj-wv** [comment]
> yes thanks, after investigating it did not work for me I saw the example of the project and updated the gradle, it would be good to notify it in README.md what version of flutter I use, version of gradle and the zoom sdk version
