### ISSUE TITLE
Error while running on ios simulator from M1 mac. Works perfectly fine for android

### ISSUE THREAD

**Issue by Uuttssaavv** [raj-wv/flutter_zoom#9]
Swift Compiler Error (Xcode): No such module 'MobileRTC'
/*base_path*/flutter_zoom/ios/Classes/SwiftFlutterZoomPlugin.swift:2:7

**Comment by raj-wv** [comment]
> Swift Compiler Error (Xcode): No such module 'MobileRTC' /_base_path_/flutter_zoom/ios/Classes/SwiftFlutterZoomPlugin.swift:2:7

you need to run on real device because i didn't configure simulator code yet

**Comment by Uuttssaavv** [comment]
The issue persists when building or archiving from xcode.
